# Generated by Django 5.1.7 on 2025-04-01 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('auth', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(max_length=3)),
                ('date', models.DateField(verbose_name=datetime.date)),
            ],
        ),
    ]
